# Background and foreground colors
background = #060606
foreground = #ffffff

# Standard colors
palette = 0=#060606
palette = 1=#5aa6ce
palette = 2=#55e2d6
palette = 3=#6dd3c6
palette = 4=#6fcae7
palette = 5=#7dcfe8
palette = 6=#86e7ee
palette = 7=#f5fdfd

# Bright colors
palette = 8=#797979
palette = 9=#9dcde6
palette = 10=#a0f3ec
palette = 11=#b1ebe4
palette = 12=#bbe8f7
palette = 13=#c9edf8
palette = 14=#d5f8fb
palette = 15=#ffffff
