$color = rgba(6, 6, 6, 1)
$inner_color = rgba(6, 6, 6, 0.66)
$outer_color = rgba(125, 207, 232, 1)
$font_color = rgba(255, 255, 255, 1)
$placeholder_color = rgba(255, 255, 255, 0.7)
$check_color = rgba(134, 231, 238, 1)
