background            #060606
foreground            #ffffff

# black
color0  #060606
color8  #797979

# red
color1  #5aa6ce
color9  #9dcde6

# green
color2  #55e2d6
color10 #a0f3ec

# yellow
color3  #6dd3c6
color11 #b1ebe4

# blue
color4  #6fcae7
color12 #bbe8f7

# magenta
color5  #7dcfe8
color13 #c9edf8

#cyan
color6  #86e7ee
color14 #d5f8fb

#white
color7  #f5fdfd
color15 #ffffff


