# Background and foreground colors
background = #020102
foreground = #ffffff

# Standard colors
palette = 0=#020102
palette = 1=#c36e65
palette = 2=#d2ad91
palette = 3=#c99175
palette = 4=#dfdfe0
palette = 5=#bca9af
palette = 6=#bfc0c1
palette = 7=#f9f7f7

# Bright colors
palette = 8=#886188
palette = 9=#dfaaa4
palette = 10=#eeddd1
palette = 11=#e5c5b5
palette = 12=#ffffff
palette = 13=#e5dcdf
palette = 14=#eeeeee
palette = 15=#ffffff
